"use client"

import {
  BookOpen,
  Code,
  FileText,
  Microscope,
  Cable as Cube,
  Users,
} from "lucide-react"

export const services = [
  {
    id: "joki-penulisan",
    title: "Joki Penulisan",
    description: "Layanan penulisan akademik profesional untuk berbagai kebutuhan",
    price: 250000,
    icon: FileText,
    category: "Academic",
    popular: false,
    features: ["Essay & Artikel", "Makalah & Paper", "Review Jurnal", "Proposal Penelitian", "Laporan Praktikum"],
    deliveryTime: "3-7 hari",
    revisions: "3x revisi gratis",
  },
  {
    id: "joki-skripsi",
    title: "Joki Skripsi",
    description: "Bantuan penyelesaian skripsi, tesis, dan disertasi dengan kualitas terbaik",
    icon: BookOpen,
    category: "Academic",
    popular: true,
    features: ["Skripsi S1", "Proposal & Bab 1-5", "Analisis Data SPSS/R"],
    deliveryTime: "2-4 minggu",
    revisions: "Revisi 4 kali",
    subOptions: [
      {
        id: "skripsi-bab1-3",
        name: "Bab 1 - 3 Saja",
        price: 900000,
        features: ["Bab 1", "Bab 2", "Bab 3"],
      },
      {
        id: "skripsi-bab4-5",
        name: "Bab 4 - 5 + Free PPT",
        price: 1800000,
        features: ["Bab 4", "Bab 5", "Free Pembuatan PPT"],
      },
    ],
  },
  {
    id: "joki-program",
    title: "Joki Pembuatan Program",
    description: "Pengembangan aplikasi dan sistem sesuai kebutuhan Anda",
    price: 1500000,
    icon: Code,
    category: "Programming",
    popular: false,
    features: ["Website & Web App", "Mobile App", "Desktop Application", "Database Design", "API Development"],
    deliveryTime: "1-3 minggu",
    revisions: "Support & konsultasi",
  },
  {
    id: "joki-jurnal",
    title: "Joki Jurnal Ilmiah",
    description: "Penulisan dan publikasi jurnal ilmiah berkualitas tinggi",
    price: 1200000,
    icon: Microscope,
    category: "Academic",
    popular: false,
    features: [
      "Jurnal Nasional",
      "Jurnal Internasional",
      "Review & Editing",
      "Bantuan Publikasi",
      "Citation Management",
    ],
    deliveryTime: "2-6 minggu",
    revisions: "5x revisi gratis",
  },
  {
    id: "joki-3d",
    title: "Joki 3D Modeling",
    description: "Pembuatan model 3D profesional untuk berbagai keperluan",
    price: 1800000,
    icon: Cube,
    category: "Design",
    popular: false,
    features: ["Architectural 3D", "Product Modeling", "Character Design", "Animation", "Rendering"],
    deliveryTime: "5-10 hari",
    revisions: "3x revisi gratis",
  },
  {
    id: "konsultasi",
    title: "Konsultasi Akademik",
    description: "Bimbingan dan konsultasi untuk berbagai kebutuhan akademik",
    price: 150000,
    icon: Users,
    category: "Consultation",
    popular: false,
    features: ["Konsultasi 1-on-1", "Review Dokumen", "Guidance & Tips", "Q&A Session", "Follow-up Support"],
    deliveryTime: "1-2 hari",
    revisions: "Unlimited chat",
  },
]

export const categories = ["All", "Academic", "Programming", "Design", "Consultation"]